database/WaterConsumptionServiceTest.java - Test 2 (Fail)
test: null activity should return zero

Output:
NullPointerException
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local5>" is null